### ISSUE TITLE
change of semantics of `hornerE`

### ISSUE THREAD

**Issue by affeldt-aist** [math-comp/trajectories#32]
https://github.com/math-comp/trajectories/blob/1b0221af1baac5e2253788c80ad8bac7b1585c86/theories/casteljau.v#L594-L598

If I am not mistaken, `hornerE` has changed with last MathComp releases, this part might need to be updated but this is a minor issue.

**Comment by ybertot** [comment]
I think we should give up backward compatibility to versions of math-comp that existed before the semantic change.  I do have a fix that is backward compatible, but that gives code that will be awkward to read in the long run.

**Comment by affeldt-aist** [comment]
You are right.

**Comment by ybertot** [comment]
fixed by #34
